### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by danzio** [DArkHekRoMaNT/HelveHammerExtensions#2]
Hi! I have some crashes recently with my helve hammer. Latest version of mod for VS 1.15.9.

Logs are here: https://0bin.net/paste/TfAZQygz#0cK-kfWhORLusx7dg6zATXbomBqQndM9dUQm/xrLz7v

**Comment by DArkHekRoMaNT** [comment]
> System.IO.IOException: Процесс не может получить доступ к файлу "C:\Users\Danil\AppData\Roaming\VintagestoryData\ModConfig\helvehammerext.json", так как этот файл используется другим процессом.

Close the config file

**Comment by danzio** [comment]
I didn't open it, actually, Haven't touched it. So I have no idea, which process could be messing with config file.

**Comment by DArkHekRoMaNT** [comment]
Fixed in v.1.1.1: No crash, the config file will simply not be saved. 
But if your files are blocked for no reason, it's strange.
