### ISSUE TITLE
Request: Config option to override items that are set to false in files

### ISSUE THREAD

**Issue by genderneutralnoun** [DArkHekRoMaNT/HelveHammerExtensions#3]
Title. I thought that AllWorkable would do this, but it doesn't seem to, as I cannot work anvil parts. I'm comfortable editing mod .jsons manually and have done so (haven't tested whether it works yet though), but not everyone is. I'm also curious what AllWorkable does if it doesn't do this.

**Comment by DArkHekRoMaNT** [comment]
Are you sure it doesn't work? Hammer will not forge if there are no voxels outside of output item blueprint
