### ISSUE TITLE
HarmonyLib compile errors in 1.17 rc8

### ISSUE THREAD

**Issue by Godlessdonut** [DArkHekRoMaNT/HelveHammerExtensions#4]
From client-main.txt:

[Error] [helvehammerext] Compiler errors during compilation:
[Error] [helvehammerext]     \src\VanillaPatches.cs(2): The type or namespace name 'HarmonyLib' could not be found (are you missing a using directive or an assembly reference?) [CS0246]
[Error] [helvehammerext]     \src\Patches\GetHelveWorkableModePatch.cs(1): The type or namespace name 'HarmonyLib' could not be found (are you missing a using directive or an assembly reference?) [CS0246]
[Error] [helvehammerext]     \src\VanillaPatches.cs(11): The type or namespace name 'Harmony' could not be found (are you missing a using directive or an assembly reference?) [CS0246]
[Error] [helvehammerext]     \src\Patches\GetHelveWorkableModePatch.cs(6): The type or namespace name 'HarmonyPatch' could not be found (are you missing a using directive or an assembly reference?) [CS0246]
[Error] [helvehammerext]     \src\Patches\GetHelveWorkableModePatch.cs(6): The type or namespace name 'HarmonyPatchAttribute' could not be found (are you missing a using directive or an assembly reference?) [CS0246]
[Error] [helvehammerext]     \src\Patches\GetHelveWorkableModePatch.cs(7): The type or namespace name 'HarmonyPatch' could not be found (are you missing a using directive or an assembly reference?) [CS0246]
[Error] [helvehammerext]     \src\Patches\GetHelveWorkableModePatch.cs(7): The type or namespace name 'HarmonyPatchAttribute' could not be found (are you missing a using directive or an assembly reference?) [CS0246]
[Error] [helvehammerext] An exception was thrown when trying to load assembly:
System.Exception: Could not compile from source files due to errors
   at Vintagestory.Common.ModCompilationContext.CompileFromFiles(ModContainer mod, IEnumerable`1 paths) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\ModCompilationContext.cs:line 70
   at Vintagestory.Common.ModContainer.LoadAssembly(ModCompilationContext compilationContext, ModAssemblyLoader loader) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\API\ModContainer.cs:line 347
[Warning] One or more source code mods failed to compile. Info to modders: In case you cannot find the problem, be aware that the game engine currently can only compile C# code until version 5.0. Any language features from C#6.0 or above will result in compile errors.

**Comment by DArkHekRoMaNT** [comment]
Fixed in 1.3.1
