### ISSUE TITLE
No process animation. 

### ISSUE THREAD

**Issue by AreYSerious** [DArkHekRoMaNT/HelveHammerExtensions#5]
VS: 1.17.3
HHE: 1.3.1

If I place an ingot in a helve hammer it doesnt show any progress its just finishes the item after given time

**Comment by DArkHekRoMaNT** [comment]
I need more info. This problem is sometimes reported, but I can't reproduce it. Perhaps the configuration of the client and server is different?

**Comment by AreYSerious** [comment]
I will test this next time I play with your mod on 1.18 and will hit you up again
